### ISSUE TITLE
Pause Functionality

### ISSUE THREAD

**Issue by joshcawthorne** [JMPerez/beats-audio-api#3]
Is there any possibility of you showing me how to add a pause button to the code? I can't work out how you're playing the audio really as I'm new to all of this!

Cheers!

**Comment by JMPerez** [comment]
@joshcawthorne Adding a pause button should be easy. I didn't include it for the basic version, but you could call the `pause()` method of the audio object to pause the playback.

**Comment by joshcawthorne** [comment]
@JMPerez Sorry, this is probably frustrating, but I can't get it going using this. I'm really new to this so I'm sure it's obvious, but I've tried a few different ways using the `pause()` method. I've followed a few stack-overflow pages etc, but everytime I make an addition to the script file, the play button instantly shows up and if I try search for the track, the page just resets as soon as I try the search.

Is there any possibility of you showing me how to actually do this?

I'd be forever in your debt!

**Comment by JMPerez** [comment]
Fixed with https://github.com/JMPerez/beats-audio-api/pull/4

**Comment by joshcawthorne** [comment]
Thank you so much!

**Comment by JMPerez** [comment]
@joshcawthorne let me know if you miss any other functionality or want to know more about how "pause" works.
