### ISSUE TITLE
Offline music source (without SpotifyAPI)

### ISSUE THREAD

**Issue by alfnitacoder** [JMPerez/beats-audio-api#9]
Hello this is very good!! i would like if you help me, i'd like to use this code but without SpotifyAPI i want to load my own music file to it. can you point me direction... please

**Comment by JMPerez** [comment]
@algeorge you would need to make a request to a local file, hosting it with the rest of the files in the project and making a request to e.g. localhost.

Another option would be to implement drag&drop and then read the contents of the file, similar to how it's done on https://github.com/JMPerez/sync-subs

**Comment by alfnitacoder** [comment]
@JMPerez thanks for help will give a try. Thankyou
